// carryOver.js — end-of-week triage (SPEC §3.6, case 3E, OD-9/13).
// Incomplete + past tasks: recurring regenerate naturally (not carried);
// deadline-passed are flagged and left; the rest re-place into the target week
// as placedBy:'auto', incrementing history.carriedCount.

import { addDays, dayStart } from './time.js';
import { intervalsOf, placeTask } from './placement.js';

/**
 * @returns { carried: Task[], missedDeadline: Task[], dropped: Task[] }
 *   dropped = recurring tasks that are regenerated by next week's expansion
 *   rather than physically moved.
 */
export function carryOver(schedule, fromWeekStart, toWeekStart, opts = {}) {
  const now = opts.now || new Date();
  const fromWs = dayStart(fromWeekStart);
  const toWs = dayStart(toWeekStart);
  const carried = [];
  const missedDeadline = [];
  const dropped = [];

  const to = addDays(toWs, schedule.config.maxPlacementLookahead + 6);

  for (const t of schedule.tasks) {
    if (t.chunking) continue;
    if (t.completion !== null) continue;
    // Belongs to the source week?
    const idx = t.getDayIndex(fromWs);
    if (idx < 0 || idx > 6) continue;
    // Only past-due (incomplete) tasks carry.
    if (t.endTime.getTime() >= now.getTime()) continue;

    if (t.recurrence) {
      dropped.push(t); // regenerated naturally by expansion — never carried
      continue;
    }
    if (t.deadline && t.deadline.getTime() < now.getTime()) {
      t.missedDeadline = true;
      missedDeadline.push(t);
      continue;
    }
    const occupied = intervalsOf(
      schedule.tasks.filter((o) => o !== t && !o.chunking && !o.recurrence && o.getDayIndex(toWs) >= 0 && o.getDayIndex(toWs) <= 6),
    );
    placeTask(schedule, t, { from: toWs, to, occupied, origin: t.startTime });
    t.placedBy = 'auto';
    t.history.carriedCount += 1;
    carried.push(t);
  }

  return { carried, missedDeadline, dropped };
}

/** "Let them go" (OD-13): mark incomplete past tasks in a week as skipped —
 *  a clean, recorded, guilt-free end state that also feeds honest ML data. */
export function letThemGo(schedule, fromWeekStart, opts = {}) {
  const now = opts.now || new Date();
  const fromWs = dayStart(fromWeekStart);
  const released = [];
  for (const t of schedule.tasks) {
    if (t.chunking || t.recurrence) continue;
    if (t.completion !== null) continue;
    const idx = t.getDayIndex(fromWs);
    if (idx < 0 || idx > 6) continue;
    if (t.endTime.getTime() >= now.getTime()) continue;
    t.completion = 'skipped';
    released.push(t);
  }
  return released;
}
